fails the installation based on test output

diff --git a/test/run_tests b/test/run_tests
--- a/test/run_tests
+++ b/test/run_tests
@@ -12,10 +12,21 @@ for file in $filelist; do
     then
         rm $current
     fi
-    
+
     echo "Building $file"
     `gcc $file ../src/*.c -o ${file:0:${#file}-2} -pthread`
     echo "Running $current"
     ./$current
-    rm $current
+    out=$?
+    if [ ! $out -eq 0 ]; then
+        echo "Test failed"
+        rm $current
+        exit 1
+
+    else
+        echo "Test passed"
+        rm $current
+    fi
 done;
+
+exit 0
